/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author 20142BSI0038
 */
public class TelaSemaforo extends javax.swing.JFrame {

    /**
     * Creates new form TelaSemaforo
     */
    public TelaSemaforo() {
        initComponents();
    }
    
    public void exibeVerde(){
        this.imagemVerde.setVisible(true);
        this.imagemAmarelo.setVisible(false);
        this.imagemVermelho.setVisible(false);
    }
    
    
    public void exibeVermelho(){
        this.imagemVerde.setVisible(false);
        this.imagemAmarelo.setVisible(false);
        this.imagemVermelho.setVisible(true);
    }
    
    public void exibeAmarelo(){
        this.imagemVerde.setVisible(false);
        this.imagemAmarelo.setVisible(true);
        this.imagemVermelho.setVisible(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemVerde = new javax.swing.JLabel();
        imagemVermelho = new javax.swing.JLabel();
        imagemAmarelo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagemVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/verde.png"))); // NOI18N
        getContentPane().add(imagemVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        imagemVermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/vermelho.png"))); // NOI18N
        getContentPane().add(imagemVermelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        imagemAmarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/amarelo.png"))); // NOI18N
        getContentPane().add(imagemAmarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSemaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSemaforo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagemAmarelo;
    private javax.swing.JLabel imagemVerde;
    private javax.swing.JLabel imagemVermelho;
    // End of variables declaration//GEN-END:variables
}
